using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Ses.UnitTests")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Ses.UnitTests")]
[assembly: AssemblyCopyright("Copyright © Dariusz Lenartowicz 2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("f4b33712-a07f-4fbc-815b-955a2d04305c")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0.0")]
